import assert from "node:assert/strict";
import { classifyProductText } from "../src/lib/products/product-category";

const cases: Array<[string, string, string | null]> = [
  ["Air Wick Essential Oil Blue Eucalyptus & Cedarwood Diffuser Refill", "Household", "Cleaning & household"],
  ["Bega Peanut Butter Smooth 470g", "Pantry", "Jams, honey & spreads"],
  ["Macro Organic Coconut Cream 400mL", "Pantry", "Canned food, soups & noodles"],
  ["Baby Mum Mum Premium Rice Rusks Banana 12+ Months 18 Pack", "Baby", "Baby food & care"],
  ["Apple, Strawberry & Blueberry Baby Rice Puffs 8+ months 45g", "Baby", "Baby food & care"],
  ["Annabel Karmel Little Meals 1-4 Years Bolognese Pasta Bake", "Baby", "Baby food & care"],
  ["Marinated Honey Soy RSPCA Approved Chicken Drumsticks 1.5kg", "Meat & seafood", "Fresh meat & seafood"],
  ["RSPCA Approved Chicken Bites With Sriracha Mayonnaise 500g", "Meat & seafood", "Fresh meat & seafood"],
  ["Lemon Pepper Atlantic Salmon Fillets 250g", "Meat & seafood", "Fresh meat & seafood"],
  ["Beef Soup Bones", "Meat & seafood", "Fresh meat & seafood"],
  ["Bitemeat Tangy Pepper Air Dried Venison", "Meat & seafood", "Fresh meat & seafood"],
  ["Canterbury Biltong Original With Coriander & Pepper Air Dried Beef", "Meat & seafood", "Fresh meat & seafood"],
  ["Honey Beef Sausages 500g", "Meat & seafood", "Fresh meat & seafood"],
  ["Blue Wave Salt & Pepper Squid", "Meat & seafood", "Fresh meat & seafood"],
  ["Lamb Shanks in Rosemary & Mint Sauce 2 Pack 1kg", "Meat & seafood", "Fresh meat & seafood"],
  ["Bertocchi Pure Boneless Virginian Honey Leg Ham", "Deli", "Deli meat & antipasto"],
  ["Arnotts Shapes Light & Crispy Honey Soy Chicken", "Pantry", "Snacks"],
  ["Arnotts Shapes Originals Cheddar", "Pantry", "Snacks"],
  ["Arnotts Vita Weat Cracked Pepper", "Pantry", "Snacks"],
  ["Belvita Strawberry Yoghurt Sandwich Breakfast Biscuits 253g 5 pack", "Pantry", "Snacks"],
  ["Fruity Filled Bars Apple & Cinnamon 6 Pack 225g", "Pantry", "Snacks"],
  ["Bains Wholefoods Gluten Free Original Flavour Chickpea Chips", "Pantry", "Snacks"],
  ["Salted Lentil Chips 120g", "Pantry", "Snacks"],
  ["On The Go Dry Roasted Honey Mixed Nuts 45g", "Pantry", "Snacks"],
  ["Snack'N'Go Chick Peas with Olive Oil, Garlic & Rosemary 70g", "Pantry", "Snacks"],
  ["Band Aid Assorted Plastic Breathable Sterile Shapes 50 Pack", "Health & personal care", "Health & personal care"],
  ["Apple Cider Vinegar Gummies 60 Pack", "Health & personal care", "Health & personal care"],
  ["Australian Botanical Soap Manuka Honey With Jojoba Oil Pure Plant Oil", "Health & personal care", "Health & personal care"],
  ["Al'Fez Moroccan Meatball Tagine Simmer Sauce Medium 425g", "Pantry", "Sauces & condiments"],
  ["Ayam Black Bean Sauce", "Pantry", "Sauces & condiments"],
  ["Ayam Thai Chilli Jam Medium Stir Fry Paste", "Pantry", "Sauces & condiments"],
  ["Ayam Thai Fried Rice Medium Rice Paste", "Pantry", "Sauces & condiments"],
  ["MasterFoods Tuscan Meatballs Recipe Base 175g", "Pantry", "Stocks, gravy & recipe bases"],
  ["Yellowfin Tuna Italian Style in Oil 185g", "Pantry", "Canned food, soups & noodles"],
  ["777 Mackerel In Tomato Sauce", "Pantry", "Canned food, soups & noodles"],
  ["Black & Gold Sardines In Vegetable Oil", "Pantry", "Canned food, soups & noodles"],
  ["Always Fresh Anchovies In Extra Virgin Olive Oil", "Pantry", "Canned food, soups & noodles"],
  ["Herring Fillets in Mustard Sauce 200g", "Pantry", "Canned food, soups & noodles"],
  ["Smoked Mussels in Galician Style Tomato Sauce 85g", "Pantry", "Canned food, soups & noodles"],
  ["Always Fresh Cucumbers Bread & Butter 700g", "Pantry", "Pickled vegetables & condiments"],
  ["Always Fresh Stuffed Olives Parmesan", "Pantry", "Pickled vegetables & condiments"],
  ["Baby Capers", "Pantry", "Pickled vegetables & condiments"],
  ["Angas Park Soft & Juice Pitted Prunes 250g", "Pantry", "Snacks"],
  ["Ardmona Rich & Thick Mixed Herbs Diced Tomatoes With Paste", "Pantry", "Canned food, soups & noodles"],
  ["Dole Premium Tropical Pineapple Chunks In Juice 227g", "Pantry", "Canned food, soups & noodles"],
  ["SPC Peaches Sliced In Juice Canned Fruit 825g", "Pantry", "Canned food, soups & noodles"],
  ["Cling Wrap 60m", "Household", "Cleaning & household"],
  ["Banana Bread Mix 400g", "Pantry", "Baking"],
  ["Anchor Lighthouse Bread & Pizza Plain Flour", "Pantry", "Baking"],
  ["Obento Panko Bread Crumbs 600g", "Pantry", "Baking"],
  ["Abbotts Bakery High Protein Soy Chickpea & Quinoa Bread", "Bakery", "Bread & bakery"],
  ["Apple & Cinnamon Muffins 4 Pack", "Bakery", "Bread & bakery"],
  ["Cinnamon Scrolls 16 Pack in Oven Safe Tray", "Bakery", "Bread & bakery"],
  ["Always Fresh Grissini Rosemary & Sea Salt Italian Bread Sticks", "Bakery", "Bread & bakery"],
  ["Always Fresh Crustini Olive Oil & Sea Salt Italian Bruschetta Toasts", "Bakery", "Bread & bakery"],
  ["Alfa One Rice Bran Oil", "Pantry", "Oils & vinegars"],
  ["Bertolli Classic Olive Oil Spread", "Dairy & eggs", "Butter & margarine"],
  ["Woolworths Peach Slices In Juice 825g", "Pantry", "Canned food, soups & noodles"],
  ["Queen Sugar Free Chocolate Fudge Topping 355mL", "Pantry", "Desserts"],
  ["Woolworths Natural Plain Waffle Cones 12 pack", "Pantry", "Desserts"],
  ["Aunt Bettys Apple Pie Rice Pudding", "Pantry", "Desserts"],
  ["Birds Eye Golden Crunch Super Crunch Chips", "Frozen", "Frozen food"],
  ["Birds Eye Golden Crunch Lattice Crispy Potato Chips", "Frozen", "Frozen food"],
  ["Birds Eye Golden Crunch Sidewinders Twisty Potato Chips", "Frozen", "Frozen food"],
  ["Coke Zero Sugar 30x375ml", "Drinks", "Cold drinks"],
  ["Chicken Mince with Rice, Carrot & Spinach Premium Puppy Food 100g", "Pet", "Dog food & care"],
  ["23rd St Signature G&T Non Alcoholic No Sugar Cans", "Other", null],
  ["50% Less Sugar Dried Cranberries 250g", "Pantry", "Snacks"],
];

for (const [name, department, shelf] of cases) {
  const actual = classifyProductText(name);
  assert.equal(actual.department, department, `${name}: expected ${department}, got ${actual.department} (${actual.reason})`);
  assert.equal(actual.shelf, shelf, `${name}: expected shelf ${shelf}, got ${actual.shelf}`);
}

console.log(`Product taxonomy regression passed: ${cases.length} cases.`);
