import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const bridge = readFileSync(new URL("../../../services/grocery-mcp/bridge.py", import.meta.url), "utf8");
const compose = readFileSync(new URL("../../../docker-compose.yml", import.meta.url), "utf8");
const hostBrowserCompose = readFileSync(new URL("../../../docker-compose.host-browser.yml", import.meta.url), "utf8");
const browserSidecar = readFileSync(new URL("../../../services/grocery-mcp/woolworths_browser.py", import.meta.url), "utf8");
const colesBrowserSidecar = readFileSync(new URL("../../../services/grocery-mcp/coles_browser.py", import.meta.url), "utf8");
const hostBrowser = readFileSync(new URL("../../../scripts/run-woolworths-host-browser.sh", import.meta.url), "utf8");
const hostBrowserService = readFileSync(new URL("../../../deploy/food-woolworths-browser.service", import.meta.url), "utf8");
const labelEnrichment = readFileSync(new URL("../src/lib/product-intelligence/retailer-label-enrichment.ts", import.meta.url), "utf8");

assert.match(bridge, /WOOLWORTHS_CATEGORY_API_PATH = "\/apis\/ui\/browse\/category"/);
assert.match(bridge, /WOOLWORTHS_COLLECTION_CATEGORIES = tuple\(/, "the known catalogue plan must be configured independently of imports");
assert.match(bridge, /"\/shop\/browse\/health-beauty": "\/shop\/browse\/beauty"/, "the obsolete health-beauty root must migrate to Woolworths's live Beauty route");
assert.doesNotMatch(bridge, /"\/shop\/browse\/health-beauty,"/, "the default collection plan must not seed the obsolete route");
assert.match(bridge, /CREATE TABLE IF NOT EXISTS woolworths_category_collection/, "collector progress must survive bridge restarts");
assert.match(bridge, /state IN \('pending', 'running', 'completed', 'failed'\)/, "collection state must distinguish resumable, complete and retryable work");
assert.match(bridge, /class WoolworthsCatalogueCollector[\s\S]*threading\.Thread/, "catalogue acquisition must be a background serial job");
assert.match(bridge, /SET state = 'pending' WHERE state = 'running'/, "a restart must release interrupted categories for safe retry");
assert.match(bridge, /if __name__ == "__main__":[\s\S]*recover_woolworths_category_collection\(\)/, "only bridge startup, not status reads, may release interrupted work");
assert.match(bridge, /\/woolworths\/catalogue\/collection\/start/, "collection must be startable without holding an HTTP request open");
assert.match(bridge, /\/woolworths\/catalogue\/collection\/status/, "collection progress must be observable");
assert.match(bridge, /requires browser verification[\s\S]*return[\s\S]*continue/, "browser verification must pause the serial queue before later checkpoints are consumed");
assert.match(bridge, /WOOLWORTHS_CATEGORY_SESSION_SECONDS = \([\s\S]*WOOLWORTHS_CATEGORY_NAVIGATION_SECONDS[\s\S]*WOOLWORTHS_CATEGORY_SCROLL_ROUNDS[\s\S]*\+ 180/, "the caller timeout must include a bounded allowance for broad-category pagination");
assert.match(bridge, /WOOLWORTHS_BROWSER_FETCH_URL = os\.getenv/, "category collection must use the dedicated visible-browser fetch endpoint");
assert.match(bridge, /urlopen\(request, timeout=WOOLWORTHS_CATEGORY_SESSION_SECONDS\)/, "every sidecar category request must have the bounded session timeout");
assert.match(bridge, /def woolworths_visible_category_fetch[\s\S]*categoryRequests[\s\S]*unpaired category capture data/, "category capture must require response/request pairs");
assert.match(bridge, /def browse\(self, category_path: str\)[\s\S]*woolworths_visible_category_fetch\(category_path\)/, "category browsing must be delegated to visible UC navigation");
assert.match(bridge, /def woolworths_remaining_category_pages[\s\S]*TotalRecordCount[\s\S]*range\(current_page \+ 1, total_pages \+ 1\)/, "broad category pagination must be derived from the authoritative finite storefront total");
assert.match(bridge, /page_size = int\(request_payload\.get\("pageSize"\)/, "leaf collection must preserve the storefront page size");
assert.match(bridge, /def woolworths_remaining_category_pages[\s\S]*TotalRecordCount[\s\S]*total_pages = \(total \+ page_size - 1\) \/\/ page_size[\s\S]*range\(current_page \+ 1, total_pages \+ 1\)/, "leaf collection must derive every remaining API page from the authoritative result total");
assert.match(bridge, /for page_number in woolworths_remaining_category_pages\([\s\S]*woolworths_visible_category_fetch\([\s\S]*woolworths_visible_category_page\(category_path, page_number\)/, "every remaining category page must navigate through the visible sidecar");
assert.match(browserSidecar, /CATEGORY_SESSION_SECONDS = \([\s\S]*CATEGORY_NAVIGATION_SECONDS[\s\S]*\+ 180/, "the sidecar must use the same bounded visible-navigation budget");
assert.match(browserSidecar, /"categoryRequests": result\.get\("categoryRequests", \[\]\)/, "the sidecar must return request metadata together with category responses");
assert.match(browserSidecar, /if request_id in self\.responses and request_id in self\.requests/, "the sidecar must never return an unpaired category response");
assert.match(browserSidecar, /Network\.requestWillBeSent[\s\S]*Network\.responseReceived[\s\S]*Network\.loadingFinished/, "the UC sidecar must track each category request through completion");
assert.match(browserSidecar, /driver\.get\(url\)/, "the visible UC browser must own each category page navigation");
assert.match(bridge, /children = woolworths_subcategory_paths\(payload, category\)[\s\S]*enqueue_woolworths_collection_categories\(children\)/, "the collector must enqueue discovered descendants during the same resumable run");
assert.match(bridge, /if children:[\s\S]*"products": 0[\s\S]*else:[\s\S]*cache_woolworths_leaf\(category, payload\)/, "parents must remain discovery-only while leaf payloads alone are cached");
assert.match(bridge, /def migrate_woolworths_collection_categories[\s\S]*DELETE FROM woolworths_category_collection WHERE category_path = \?/, "persisted obsolete roots must not leave collection status permanently failed");
assert.match(bridge, /revisitCompletedRoots/, "previously completed roots must be safely revisitible to seed descendants");
assert.match(bridge, /WHERE state = 'completed' AND category_path IN/, "revisiting roots must not reset completed descendants");
assert.match(bridge, /CREATE TABLE IF NOT EXISTS woolworths_product_categories/, "every observed Woolworths category path must be retained per stockcode");
assert.match(bridge, /PRIMARY KEY \(stockcode, category_path\)/, "a stockcode may be associated with multiple source category paths without duplicates");
assert.match(bridge, /INSERT INTO woolworths_product_categories[\s\S]*ON CONFLICT\(stockcode, category_path\)/, "category observations must be safely refreshable");
assert.match(bridge, /product\["category_paths"\]/, "controlled imports must receive all source category paths for each stockcode");
assert.match(bridge, /revisitAllCompleted/, "the collector must support a full completed-category rescan for source reindexing");
assert.match(bridge, /WHERE state = 'completed'\r?\n\s*"""/, "a full rescan must revisit every completed category, not only roots");
assert.match(bridge, /woolworths_product_nodes\(payload\)/, "nested Bundles and Products must be flattened");
assert.match(bridge, /stockcode TEXT PRIMARY KEY, barcode TEXT/, "stock codes and barcodes must remain exact text");
assert.match(bridge, /ON CONFLICT\(stockcode\) DO UPDATE/, "category refreshes must be resumable and idempotent");
assert.match(bridge, /def woolworths_category_priority[\s\S]*"pet": 100[\s\S]*"freezer": 80/, "specific Woolworths departments must not be overwritten by a later pantry browse page");
assert.match(bridge, /create_function\("woolworths_category_priority", 1, woolworths_category_priority\)/, "the category-priority function must be available to the SQLite upsert");
assert.match(bridge, /WOOLWORTHS_DETAIL_API_PATH = "\/apis\/ui\/product\/detail"/, "details must come from Woolworths's authoritative product endpoint");
assert.match(bridge, /def cache_woolworths_details[\s\S]*brand[\s\S]*long_description[\s\S]*ingredients[\s\S]*allergens[\s\S]*nutrition[\s\S]*dietary_claims[\s\S]*country_of_origin[\s\S]*storage_instructions[\s\S]*preparation_instructions[\s\S]*additional_images/, "all requested detail fields must be persisted");
assert.match(bridge, /else:\s*\r?\n\s*outcome = cache_woolworths_leaf\(category, payload\)/, "leaf collection must checkpoint the complete category without waiting for per-product details");
assert.match(bridge, /class WoolworthsDetailCollector[\s\S]*woolworths_browser\(\)\.details\(stockcodes\)[\s\S]*cache_woolworths_details\(results\)/, "rich details must run through a separate resumable collector");
assert.match(bridge, /if row is None:[\s\S]*_woolworths_detail_collector\.start\(\)[\s\S]*return/, "detail enrichment must begin only after catalogue navigation has finished");
assert.match(bridge, /detailsEnriched[\s\S]*detailsFailed/, "partial detail coverage must be observable");
assert.match(bridge, /def woolworths_detail_collection_status[\s\S]*detail_refreshed_at IS NULL[\s\S]*detail_error IS NOT NULL[\s\S]*pending/, "deferred detail progress and failures must be observable");
assert.match(bridge, /\/woolworths\/catalogue\/details\/start/, "deferred detail enrichment must be explicitly resumable after a bridge restart");
assert.match(bridge, /\/woolworths\/catalogue\/product/, "cached rich product details must be readable without another live request");
assert.match(bridge, /def woolworths_cached_products[\s\S]*locally verified cache only/, "controlled imports must enumerate only the verified local cache");
assert.match(bridge, /\/woolworths\/catalogue\/products/, "controlled imports need a bounded cached catalogue endpoint");
assert.match(bridge, /detailedProducts[\s\S]*detailFailures[\s\S]*lastDetailRefreshedAt/, "detail coverage and retry failures must be visible in catalogue status");
assert.match(labelEnrichment, /fetchCachedWoolworthsLabelSource[\s\S]*\/woolworths\/catalogue\/product/, "Food label enrichment must consume the verified Woolworths detail cache");
assert.match(bridge, /cached = search_woolworths_cache[\s\S]*if cached:[\s\S]*return cached/, "search must prefer the local catalogue");
const cacheLookup = bridge.indexOf("cached = search_woolworths_cache");
const circuitLookup = bridge.indexOf("unavailable_for = _woolworths_unavailable_until");
assert.ok(cacheLookup >= 0 && cacheLookup < circuitLookup, "the local catalogue must remain searchable while the live circuit is open");
assert.match(bridge, /stockcode = \? OR barcode = \?/, "stockcode and barcode searches must be exact");
assert.match(bridge, /\/woolworths\/catalogue\/status/, "catalogue coverage must be observable");
assert.match(bridge, /WOOLWORTHS_CDP_URL = os\.getenv/, "the separate search/detail browser connection must remain configurable");
assert.match(bridge, /resolved_cdp_url\(WOOLWORTHS_CDP_URL\)[\s\S]*chromium\.connect_over_cdp\(/, "search and detail enrichment must retain the existing verified-browser connection");
assert.match(bridge, /socket\.gethostbyname\(parsed\.hostname\)/, "Docker's browser hostname must become an IP Host header accepted by Chromium");
assert.match(bridge, /verified browser fetch session is not configured/, "category refreshes without the visible sidecar must fail with an actionable reason");
assert.match(bridge, /browser is not None and owns_browser/, "the bridge must never close the user's external browser");
assert.match(compose, /WOOLWORTHS_CDP_URL: \$\{WOOLWORTHS_CDP_URL:-http:\/\/food-woolworths-browser:9223\}/);
assert.match(compose, /\$\{NOVNC_BIND_ADDRESS:-127\.0\.0\.1\}:\$\{WOOLWORTHS_NOVNC_PORT:-6081\}:6080/, "noVNC must default to host-loopback binding while allowing an explicit host override");
assert.match(compose, /food_woolworths_browser_profile:\/browser-profile/, "the verified browser profile must survive container replacement");
assert.match(browserSidecar, /undetected_chromedriver as uc/, "the sidecar must own category navigation through undetected Chrome");
assert.match(browserSidecar, /TCP-LISTEN:\{CDP_RELAY_PORT\}[\s\S]*CDP_RELAY_BIND_ADDRESS/, "the sidecar must relay Chromium's loopback CDP socket through a configurable bind address");
assert.match(browserSidecar, /TCP:127\.0\.0\.1:\{CDP_PORT\}/, "the CDP relay must terminate at Chromium's loopback socket");
assert.match(browserSidecar, /port=CDP_PORT/, "the UC-owned browser must expose its CDP socket only through the private relay");
assert.match(browserSidecar, /websockify/, "the verified browser must be visible through noVNC");
assert.match(browserSidecar, /WOOLWORTHS_BROWSER_SCREEN", "1920x1080x24"/, "the Woolworths VNC desktop must expose a full-HD page by default");
assert.match(browserSidecar, /"-screen", "0", SCREEN/, "the Woolworths virtual display must use the configurable desktop size");
assert.match(colesBrowserSidecar, /COLES_BROWSER_SCREEN", "1920x1080x24"/, "the Coles VNC desktop must expose a full-HD page by default");
assert.match(colesBrowserSidecar, /COLES_BROWSER_WINDOW_SIZE", "1920,1080"/, "the Coles browser window must fill the full-HD virtual desktop by default");
assert.match(hostBrowser, /WOOLWORTHS_HOST_SCREEN:-1920x1080x24/, "the accepted host Woolworths browser must also use a full-HD desktop by default");
assert.match(hostBrowserCompose, /network_mode: host/, "the grocery bridge must reach host loopback without publishing CDP");
assert.match(hostBrowserCompose, /ports: !reset \[\]/, "host mode must not retain redundant published ports");
assert.match(hostBrowserCompose, /WOOLWORTHS_CDP_URL:.*http:\/\/127\.0\.0\.1:9224/, "host browser mode must use loopback CDP");
assert.match(hostBrowserCompose, /WOOLWORTHS_BROWSER_FETCH_URL:.*http:\/\/127\.0\.0\.1:8791\/fetch/, "host browser mode must use its dedicated loopback UC fetch endpoint");
assert.match(hostBrowser, /woolworths_browser\.py/, "host browser mode must run the UC sidecar that serves visible category fetches");
assert.match(hostBrowser, /WOOLWORTHS_BROWSER_CDP_PORT="\$\{WOOLWORTHS_HOST_CDP_PORT:-9224\}"/, "host UC CDP must retain the configured loopback port");
assert.match(hostBrowser, /food-woolworths-profile/, "host UC must retain its accepted profile");
assert.match(hostBrowser, /WOOLWORTHS_BROWSER_NOVNC_BIND_ADDRESS="127\.0\.0\.1"/, "host noVNC must remain loopback-only");
assert.match(hostBrowser, /WOOLWORTHS_BROWSER_FETCH_BIND_ADDRESS="127\.0\.0\.1"/, "host category fetch must remain loopback-only");
assert.match(hostBrowser, /WOOLWORTHS_HOST_FETCH_PORT:-8791/, "host UC fetch must not collide with the legacy Docker sidecar");
assert.match(hostBrowser, /WOOLWORTHS_BROWSER_PYTHON:-python3/, "host sidecar must support an isolated Python runtime");
assert.match(hostBrowserService, /ExecStart=.*run-woolworths-host-browser\.sh/, "the accepted host browser must restart with the server");
assert.match(hostBrowserService, /WOOLWORTHS_BROWSER_PYTHON=.*\.venv-woolworths-browser\/bin\/python/, "the host UC service must not modify Coffee's system Python");
assert.match(bridge, /page\.evaluate\("window\.scrollTo/, "category discovery must load paginated or lazy product bundles");
assert.match(compose, /WOOLWORTHS_CATALOGUE_DB: \/data\/woolworths-catalogue\.sqlite3/);
assert.match(compose, /food_grocery_catalogue_data:\/data/);

console.log("Woolworths catalogue ingestion safeguards passed.");
