export type HwqSnackNutrition = {
  energyKj: number;
  fatGrams?: number;
  saturatedFatGrams: number;
  carbsGrams: number;
  sugarGrams: number;
  fibreGrams: number;
  proteinGrams: number;
  sodiumMg?: number;
};

export type HwqSnackRecipe = {
  id: string;
  name: string;
  style: "Savoury" | "Sweet";
  imageUrl: string;
  sourceUrl: string;
  description: string;
  servings: number;
  servingSizeGrams: number;
  vegetableServes: number;
  fruitServes: number;
  tags: string[];
  ingredients: string[];
  instructions: string[];
  notes: string[];
  nutrition: HwqSnackNutrition;
};

export const hwqSnackRecipes: HwqSnackRecipe[] = [
  {
    id: "hwq-cottage-cheese-muffins",
    name: "Cottage Cheese Muffins",
    style: "Savoury",
    imageUrl: "/recipes/hwq/cottage-cheese-muffins.webp",
    sourceUrl: "https://hw.qld.gov.au/healthy-recipes/cottage-cheese-muffins/",
    description: "Golden vegetable muffins designed as an easy make-ahead snack.",
    servings: 6,
    servingSizeGrams: 159,
    vegetableServes: 1,
    fruitServes: 0,
    tags: ["Snack", "Savoury", "Vegetarian", "Gluten Free", "Nut Free"],
    ingredients: ["Spray oil", "250g frozen chopped spinach, thawed", "6 eggs, whisked", "½ cup low-fat cottage cheese", "2 spring onions, thinly sliced", "½ cup fresh basil leaves, shredded", "1 cup cherry tomatoes, halved"],
    instructions: ["Pre-heat oven to 180°C (160°C fan-forced). Lightly spray six holes of a 1 cup (250mL) muffin pan with spray oil.", "Squeeze the thawed spinach over a colander to remove excess liquid, then transfer to a large mixing bowl.", "Add the eggs, cottage cheese, spring onion and basil and mix to combine.", "Divide the mixture between the prepared muffin holes and press the cherry tomatoes into the tops.", "Bake for 25 minutes or until golden and firm to touch. Allow to cool before serving."],
    notes: ["For dairy free, replace the cottage cheese with ½ cup grated firm tofu.", "Cherry tomatoes can be swapped for one large tomato, and spring onions for ¼ red onion.", "Other vegetables such as grated zucchini, chopped capsicum or grated carrot can be used.", "Refrigerate in an airtight container for up to 3 days."],
    nutrition: { energyKj: 423, fatGrams: 4.9, saturatedFatGrams: 1.4, carbsGrams: 4.3, sugarGrams: 2.4, fibreGrams: 2.6, proteinGrams: 10.2, sodiumMg: 153 },
  },
  {
    id: "hwq-roasted-pumpkin-hummus",
    name: "Roasted Pumpkin Hummus",
    style: "Savoury",
    imageUrl: "/recipes/hwq/roasted-pumpkin-hummus.webp",
    sourceUrl: "https://hw.qld.gov.au/healthy-recipes/roast-pumpkin-hummus/",
    description: "A versatile pumpkin and chickpea dip for vegetable sticks, wraps, sandwiches or salads.",
    servings: 8,
    servingSizeGrams: 93,
    vegetableServes: 0,
    fruitServes: 0.5,
    tags: ["Snack", "Savoury", "Vegan", "Dairy Free", "Gluten Free", "Nut Free"],
    ingredients: ["1½ cups pumpkin, peeled and cubed", "400g can chickpeas, rinsed and drained", "1 tsp cumin powder", "1 lemon, juiced", "1 tbsp tahini", "3 tbsp olive oil", "2 cloves garlic", "½ tsp reduced salt vegetable stock powder", "Pepper, to taste", "Pepitas, to serve (optional)", "Vegetable sticks, to serve"],
    instructions: ["Preheat oven to 180°C and line a baking tray with baking paper.", "Toss pumpkin with 1 tablespoon olive oil and bake for 25 minutes. Set aside to cool.", "Add roasted pumpkin, chickpeas, cumin, lemon juice, tahini, remaining olive oil, garlic, stock powder and pepper to a food processor and blend until smooth.", "Transfer to a bowl, sprinkle with pepitas if using, and serve with vegetable sticks."],
    notes: ["Check packaged ingredients are gluten free when preparing a gluten-free version.", "Use vegetable sticks such as carrot, celery, cucumber, green beans, capsicum or snow peas.", "Store in an airtight container in the fridge for up to 3 days.", "Adapted by Health and Wellbeing Queensland from a Queensland Country Women’s Association Country Kitchens recipe."],
    nutrition: { energyKj: 552, fatGrams: 9.3, saturatedFatGrams: 1.4, carbsGrams: 7.1, sugarGrams: 2.6, fibreGrams: 3.4, proteinGrams: 3.1 },
  },
  {
    id: "hwq-salmon-leek-frittata",
    name: "Salmon and Leek Frittata",
    style: "Savoury",
    imageUrl: "/recipes/hwq/salmon-leek-frittata.webp",
    sourceUrl: "https://hw.qld.gov.au/healthy-recipes/salmon-and-leek-frittata/",
    description: "A salmon, potato and leek frittata made for easy snacking through the week.",
    servings: 8,
    servingSizeGrams: 152,
    vegetableServes: 0.6,
    fruitServes: 0,
    tags: ["Snack", "Savoury", "Gluten Free", "Nut Free", "Fish"],
    ingredients: ["1 tbsp olive oil", "2 medium potatoes, thinly sliced", "1 medium leek, thinly sliced", "6 eggs", "½ cup low-fat milk", "¼ cup fresh dill, roughly chopped", "½ tsp cracked pepper", "¾ cup frozen green peas, thawed", "200g canned salmon in springwater, drained"],
    instructions: ["Pre-heat oven to 200°C (180°C fan-forced). Line a 15cm x 30cm slice pan with baking paper.", "Heat olive oil in a large non-stick saucepan over moderate heat. Add potatoes and leek and cook for 5–6 minutes or until softened.", "Scatter the vegetables over the base of the prepared pan.", "Lightly whisk eggs, milk, dill and pepper. Pour over the vegetables, then press peas and salmon into the top.", "Bake for 45 minutes or until golden and firm. Cool, then cut into 8 slices."],
    notes: ["For dairy free, use a calcium-fortified non-dairy milk alternative.", "Leek can be replaced with sliced brown onion and fresh dill with 1 tsp dried dill.", "Other vegetables such as grated zucchini, frozen spinach or canned corn can be used.", "Refrigerate in an airtight container for up to 4 days."],
    nutrition: { energyKj: 527, fatGrams: 5.7, saturatedFatGrams: 1.3, carbsGrams: 7.3, sugarGrams: 3.1, fibreGrams: 2.4, proteinGrams: 10.1, sodiumMg: 126 },
  },
  {
    id: "hwq-lentil-sweet-potato-patties",
    name: "Lentil and Sweet Potato Patties",
    style: "Savoury",
    imageUrl: "/recipes/hwq/lentil-sweet-potato-patties.webp",
    sourceUrl: "https://hw.qld.gov.au/healthy-recipes/lentil-and-sweet-potato-patties/",
    description: "Plant-based sweet potato and lentil patties that are easy to grab on the go.",
    servings: 6,
    servingSizeGrams: 222,
    vegetableServes: 1.5,
    fruitServes: 0,
    tags: ["Snack", "Savoury", "Vegan", "Dairy Free", "Nut Free"],
    ingredients: ["2 medium sweet potatoes, peeled and cut into 2cm cubes", "½ tsp ground cumin", "½ tsp smoked paprika", "½ tsp cracked pepper", "400g can brown lentils, rinsed and drained", "60g baby spinach, shredded", "¼ cup wholemeal plain flour", "2 tsp olive oil", "1 lemon, cut into wedges"],
    instructions: ["Cook sweet potato in boiling water for 10 minutes or until tender. Drain and mash until smooth.", "Add cumin, paprika, pepper, lentils, spinach and flour and mix to combine.", "Using damp hands, shape into 12 patties about 2cm thick.", "Heat oil in a large non-stick frypan over medium-high heat. Cook patties in batches for 2–3 minutes each side or until golden.", "Serve with lemon wedges."],
    notes: ["For gluten free, replace plain flour with gluten-free flour, almond meal or crushed corn flakes.", "Serve with low-fat Greek yoghurt for dipping if desired.", "The patties also work as a sandwich or wrap filling with fresh vegetables.", "Refrigerate in an airtight container for up to 3 days."],
    nutrition: { energyKj: 772, fatGrams: 2.2, saturatedFatGrams: 0.3, carbsGrams: 29.9, sugarGrams: 8.7, fibreGrams: 7.7, proteinGrams: 7, sodiumMg: 166 },
  },
  {
    id: "hwq-spiced-mixed-nuts",
    name: "Spiced Mixed Nuts",
    style: "Savoury",
    imageUrl: "/recipes/hwq/spiced-mixed-nuts.webp",
    sourceUrl: "https://hw.qld.gov.au/healthy-recipes/spiced-mixed-nuts/",
    description: "Unsalted mixed nuts toasted with cinnamon and honey.",
    servings: 20,
    servingSizeGrams: 22,
    vegetableServes: 0,
    fruitServes: 0,
    tags: ["Snack", "Savoury", "Gluten Free", "Dairy Free"],
    ingredients: ["1½ tbsp honey", "1 tbsp olive oil", "1 tsp ground cinnamon", "3 cups mixed unsalted raw nuts"],
    instructions: ["Pre-heat oven to 180°C (160°C fan-forced).", "Whisk honey, olive oil and cinnamon together in a medium mixing bowl.", "Add nuts one cup at a time, mixing well to coat before adding the next cup.", "Spread in an even layer on a large baking tray and bake for 12–15 minutes until toasted and fragrant.", "Cool before storing in an airtight container."],
    notes: ["For vegan, replace honey with pure maple syrup.", "Use any combination of unsalted raw nuts such as cashews, almonds, hazelnuts or walnuts.", "Serve alongside a piece of fruit or vegetable sticks.", "Store airtight at room temperature for up to 3 weeks."],
    nutrition: { energyKj: 567, fatGrams: 12, saturatedFatGrams: 1.2, carbsGrams: 3.4, sugarGrams: 2.6, fibreGrams: 1.7, proteinGrams: 3.2, sodiumMg: 1 },
  },
  {
    id: "hwq-avocado-salsa-pita-chips",
    name: "Avocado Salsa and Pita Chips",
    style: "Savoury",
    imageUrl: "/recipes/hwq/avocado-salsa-pita-chips.webp",
    sourceUrl: "https://hw.qld.gov.au/healthy-recipes/avocado-salsa-and-pita-chips/",
    description: "Fresh avocado salsa with homemade pita chips as a lower-salt alternative to packaged corn chips.",
    servings: 12,
    servingSizeGrams: 126,
    vegetableServes: 1,
    fruitServes: 0,
    tags: ["Snack", "Savoury", "Vegan", "Dairy Free", "Nut Free"],
    ingredients: ["8 pita breads", "3 avocados, destoned and roughly chopped", "1 medium tomato, finely chopped", "2 long red chillies, deseeded and finely diced", "1 bunch coriander, chopped", "½ red onion, finely diced", "½ cup corn kernels", "2 limes, juiced", "Pepper"],
    instructions: ["Preheat oven to 180°C.", "Cut pita bread into triangles, place on a tray and bake for 10–15 minutes or until golden and crispy.", "Combine remaining ingredients in a bowl and season with pepper.", "Garnish with extra coriander and chilli and serve with pita chips."],
    notes: ["For gluten free, use gluten-free pita bread or suitable crackers.", "Add vegetable sticks for extra vegetables.", "Store the salsa airtight in the fridge for up to 2 days, with plastic wrap pressed onto the surface to reduce browning."],
    nutrition: { energyKj: 782, fatGrams: 6.3, saturatedFatGrams: 1, carbsGrams: 23.7, sugarGrams: 2.6, fibreGrams: 7, proteinGrams: 5.1, sodiumMg: 213 },
  },
  {
    id: "hwq-chicken-veg-nuggets",
    name: "Chicken and Veg Nuggets",
    style: "Savoury",
    imageUrl: "/recipes/hwq/chicken-veg-nuggets.webp",
    sourceUrl: "https://hw.qld.gov.au/healthy-recipes/chicken-and-veg-nuggets/",
    description: "Chicken nuggets packed with spinach, zucchini and carrot, served with a yoghurt dipping sauce.",
    servings: 5,
    servingSizeGrams: 212,
    vegetableServes: 1.2,
    fruitServes: 0,
    tags: ["Snack", "Savoury", "Gluten Free", "Nut Free", "Lean protein"],
    ingredients: ["125g frozen chopped spinach, thawed", "1 zucchini, grated", "1 carrot, grated", "400g chicken mince", "2 spring onions, finely sliced", "¼ cup fresh flat-leaf parsley, shredded", "2 garlic cloves, minced", "2 tsp olive oil", "½ cup low-fat Greek yoghurt", "1 small garlic clove, minced", "¼ cup fresh flat-leaf parsley, shredded", "½ tsp cracked pepper"],
    instructions: ["Squeeze spinach, zucchini and carrot over a colander to remove excess liquid, then transfer to a large bowl.", "Add chicken mince, spring onion, parsley and garlic and mix well.", "Using damp hands, shape into 20 small nuggets.", "Heat oil in a large non-stick frypan over medium-high heat and cook in batches for 2–3 minutes each side or until golden brown.", "Combine yoghurt, garlic, parsley and pepper in a small bowl to make the dipping sauce."],
    notes: ["Vegetables can be swapped for grated sweet potato or finely diced cauliflower or broccoli.", "Serve with fresh carrot, cucumber or capsicum sticks.", "Spring onion can be replaced with ¼ brown onion and fresh parsley with dried parsley.", "Refrigerate airtight for up to 3 days or freeze for up to 2 months."],
    nutrition: { energyKj: 743, fatGrams: 7.6, saturatedFatGrams: 2.2, carbsGrams: 7.2, sugarGrams: 5, fibreGrams: 3.5, proteinGrams: 19.2, sodiumMg: 112 },
  },
  {
    id: "hwq-mexi-bean-salad-cups",
    name: "Mexi-bean Salad Cups",
    style: "Savoury",
    imageUrl: "/recipes/hwq/mexi-bean-salad-cups.webp",
    sourceUrl: "https://hw.qld.gov.au/healthy-recipes/mexi-bean-salad-cups/",
    description: "A Mexican-inspired black bean and corn salad full of fresh colourful vegetables.",
    servings: 6,
    servingSizeGrams: 231,
    vegetableServes: 2,
    fruitServes: 0,
    tags: ["Snack", "Savoury", "Vegan", "Dairy Free", "Gluten Free", "Nut Free"],
    ingredients: ["400g can black beans, rinsed and drained", "420g can no added salt corn kernels, rinsed and drained", "¼ small red onion, finely diced", "1 medium Lebanese cucumber, finely diced", "1 medium red capsicum, finely diced", "2 small tomatoes, finely diced", "1 cup fresh coriander leaves, shredded", "1 lime, juiced", "1½ tbsp olive oil", "½ tsp chilli powder", "½ tsp cracked pepper"],
    instructions: ["Combine black beans, corn, red onion, cucumber, capsicum, tomatoes and coriander in a large mixing bowl.", "Place lime juice, olive oil, chilli powder and cracked pepper in a small jar and shake to combine.", "Pour dressing over the salad just before serving."],
    notes: ["Add diced avocado if eating soon after preparation.", "Black beans can be replaced with red kidney beans or four bean mix.", "Serve alone, as a dip with toasted pita, in a wholemeal wrap, or as a side salad with grilled chicken or fish.", "Refrigerate the undressed salad airtight for up to 4 days and store dressing separately."],
    nutrition: { energyKj: 676, fatGrams: 5.8, saturatedFatGrams: 0.9, carbsGrams: 18.3, sugarGrams: 7.3, fibreGrams: 6.6, proteinGrams: 6.9, sodiumMg: 40 },
  },
  {
    id: "hwq-whipped-ricotta-roasted-tomatoes",
    name: "Whipped Ricotta and Roasted Tomatoes",
    style: "Savoury",
    imageUrl: "/recipes/hwq/whipped-ricotta-roasted-tomatoes.webp",
    sourceUrl: "https://hw.qld.gov.au/healthy-recipes/whipped-ricotta-and-roasted-tomatoes/",
    description: "Whipped ricotta topped with roasted tomatoes and onion, served with wholegrain bread.",
    servings: 10,
    servingSizeGrams: 103,
    vegetableServes: 0.6,
    fruitServes: 0,
    tags: ["Snack", "Savoury", "Vegetarian", "Nut Free"],
    ingredients: ["250g cherry tomatoes, halved", "1 red onion, diced", "1 tbsp olive oil", "2 tbsp balsamic vinegar", "375g low-fat ricotta cheese", "2 tbsp parmesan cheese", "1 small lemon, zested", "½ cup fresh basil leaves", "½ wholegrain baguette, thinly sliced"],
    instructions: ["Pre-heat oven to 200°C (180°C fan-forced).", "Place tomatoes and onion in a baking dish, drizzle with olive oil and balsamic vinegar and toss lightly.", "Bake for 15 minutes, then set aside to cool.", "Blitz ricotta, parmesan and lemon zest in a small food processor until smooth.", "Transfer ricotta to a serving dish, spoon roasted tomatoes into the centre, top with basil and serve with sliced bread."],
    notes: ["For gluten free, replace the baguette with a gluten-free alternative.", "Cherry tomatoes can be swapped for grape or snacking tomatoes.", "Use an electric mixer or blender instead of a food processor if needed.", "Serve with wholegrain crackers or vegetable sticks for extra variety."],
    nutrition: { energyKj: 426, fatGrams: 4.2, saturatedFatGrams: 1.3, carbsGrams: 8.9, sugarGrams: 2.9, fibreGrams: 2, proteinGrams: 5.4, sodiumMg: 139 },
  },
  {
    id: "hwq-pizza-scrolls",
    name: "Pizza Scrolls",
    style: "Savoury",
    imageUrl: "/recipes/hwq/pizza-scrolls.webp",
    sourceUrl: "https://hw.qld.gov.au/healthy-recipes/pizza-scrolls/",
    description: "Wholemeal pizza scrolls filled with tomato, capsicum, onion and cheese.",
    servings: 10,
    servingSizeGrams: 120,
    vegetableServes: 0.5,
    fruitServes: 0,
    tags: ["Snack", "Savoury", "Vegetarian", "Nut Free", "Lunchbox"],
    ingredients: ["1 cup wholemeal self-raising flour", "½ cup plain self-raising flour", "¾ cup low-fat Greek yoghurt", "¼ cup no added salt tomato paste", "¾ cup low-fat grated tasty cheese", "2 medium tomatoes, finely diced", "1 medium green capsicum, finely diced", "¼ red onion, finely diced", "1 tsp dried oregano", "1 tbsp low-fat milk, for brushing"],
    instructions: ["Pre-heat oven to 200°C (180°C fan-forced) and line a large tray with baking paper.", "Combine both flours and yoghurt until just combined, then lightly knead into a ball.", "Roll dough into a rectangle about 1cm thick.", "Spread with tomato paste and top with tomatoes, capsicum, onion, oregano and cheese.", "Roll into a log, cut into 10 rounds about 2cm thick, place on tray and brush with milk.", "Bake for 30 minutes or until golden and firm. Cool on a wire rack."],
    notes: ["For gluten free, replace both flours with gluten-free self-raising flour.", "Swap vegetables for other pizza toppings such as pineapple, olives, mushrooms or cherry tomatoes.", "Refrigerate airtight for up to 3 days or freeze individually for up to 2 months."],
    nutrition: { energyKj: 580, fatGrams: 3.1, saturatedFatGrams: 1.9, carbsGrams: 18.7, sugarGrams: 4.6, fibreGrams: 3.8, proteinGrams: 7.3, sodiumMg: 228 },
  },
  {
    id: "hwq-corn-tomato-cheese-loaf",
    name: "Corn, Tomato and Cheese Loaf",
    style: "Savoury",
    imageUrl: "/recipes/hwq/corn-tomato-cheese-loaf.webp",
    sourceUrl: "https://hw.qld.gov.au/healthy-recipes/corn-tomato-and-cheese-loaf/",
    description: "A savoury corn loaf with spring onion, cheese, parsley and sundried tomato.",
    servings: 10,
    servingSizeGrams: 91,
    vegetableServes: 0.5,
    fruitServes: 0,
    tags: ["Snack", "Savoury", "Vegetarian", "Nut Free"],
    ingredients: ["¾ cup self-raising flour", "¾ cup wholemeal self-raising flour", "½ cup fresh flat-leaf parsley, finely chopped", "4 spring onions, thinly sliced", "¼ cup semi-sundried tomatoes, drained and sliced", "¼ cup low-fat tasty cheese, grated", "2 cups no added salt corn kernels, rinsed and drained", "½ cup low-fat milk", "1 tbsp olive oil", "1 egg, whisked"],
    instructions: ["Pre-heat oven to 200°C (180°C fan-forced). Line an 8cm x 22cm loaf pan with baking paper.", "Sift flours into a large bowl and add parsley, spring onion, sundried tomatoes and cheese. Make a well in the centre.", "Pulse corn to a chunky consistency, then add milk, olive oil and egg and pulse again to combine.", "Add corn mixture to the dry ingredients and mix until just combined.", "Bake for 55–60 minutes or until a skewer comes out clean. Stand 10 minutes, cool on a wire rack and slice into 10 pieces."],
    notes: ["For gluten free, use gluten-free self-raising flour.", "Spring onion can be swapped for red onion and sundried tomato for fresh diced tomato.", "For dairy free, use a calcium-fortified non-dairy milk and omit the cheese.", "Refrigerate airtight for up to 3 days or freeze individual slices for up to 2 months."],
    nutrition: { energyKj: 577, fatGrams: 4, saturatedFatGrams: 1.1, carbsGrams: 18.8, sugarGrams: 2.7, fibreGrams: 2.9, proteinGrams: 5.2, sodiumMg: 180 },
  },
  {
    id: "hwq-yoghurt-bark",
    name: "Yoghurt Bark",
    style: "Sweet",
    imageUrl: "/recipes/hwq/yoghurt-bark.webp",
    sourceUrl: "https://hw.qld.gov.au/healthy-recipes/yoghurt-bark/",
    description: "Frozen Greek yoghurt topped with strawberries, kiwifruit, pistachios and dried cranberries.",
    servings: 8,
    servingSizeGrams: 164,
    vegetableServes: 0,
    fruitServes: 0.6,
    tags: ["Snack", "Sweet", "Vegetarian", "Gluten Free"],
    ingredients: ["3 cups reduced fat Greek yoghurt", "⅓ cup unsalted pistachios, chopped", "250g strawberries, thinly sliced", "3 kiwifruits, peeled and thinly sliced", "1 tbsp dried cranberries"],
    instructions: ["Line a tray with baking paper and spread yoghurt evenly over the tray.", "Arrange strawberries and kiwifruit on the yoghurt and sprinkle over nuts and dried fruit.", "Freeze until solid, about 3–4 hours or ideally overnight.", "Break into pieces to serve and return unused pieces to the freezer promptly."],
    notes: ["Swap fruit for other seasonal options such as berries, mango, peach, passionfruit or plum.", "Store pieces in an airtight container or zip-lock bag in the freezer for up to 3 months."],
    nutrition: { energyKj: 607, fatGrams: 4.7, saturatedFatGrams: 1.6, carbsGrams: 13.9, sugarGrams: 13.2, fibreGrams: 4.1, proteinGrams: 8.8, sodiumMg: 108 },
  },
  {
    id: "hwq-banana-bread",
    name: "Banana Bread",
    style: "Sweet",
    imageUrl: "/recipes/hwq/banana-bread.webp",
    sourceUrl: "https://hw.qld.gov.au/healthy-recipes/banana-bread/",
    description: "A one-bowl banana bread made with wholemeal flour, dates and cinnamon.",
    servings: 16,
    servingSizeGrams: 66,
    vegetableServes: 0,
    fruitServes: 0.5,
    tags: ["Snack", "Sweet", "Vegetarian", "Nut Free"],
    ingredients: ["4 ripe bananas", "1 tsp vanilla extract", "2 eggs", "½ cup low-fat milk", "2 tbsp canola oil", "1 cup self-raising flour", "1 cup wholemeal self-raising flour", "1 tsp ground cinnamon", "125g dried pitted dates, roughly chopped"],
    instructions: ["Pre-heat oven to 190°C (170°C fan-forced). Line an 8cm x 22cm loaf pan with baking paper.", "Mash 3 bananas in a large mixing bowl.", "Add vanilla, eggs, milk and oil and mix to combine.", "Sift in both flours and cinnamon, add dates and mix until just combined.", "Pour into pan. Slice remaining banana in half and press lightly into the top.", "Bake for 50–55 minutes or until a skewer comes out clean. Cool 10 minutes, turn onto a rack and cut into 16 pieces."],
    notes: ["For dairy free, use a calcium-fortified non-dairy milk alternative.", "For gluten free, use gluten-free self-raising flour.", "Refrigerate airtight for up to 3 days or freeze individual slices for up to 2 months."],
    nutrition: { energyKj: 583, fatGrams: 3.3, saturatedFatGrams: 0.4, carbsGrams: 23, sugarGrams: 8.5, fibreGrams: 2.7, proteinGrams: 3.2, sodiumMg: 132 },
  },
  {
    id: "hwq-mini-apple-pies",
    name: "Mini Apple Pies",
    style: "Sweet",
    imageUrl: "/recipes/hwq/mini-apple-pies.webp",
    sourceUrl: "https://hw.qld.gov.au/healthy-recipes/mini-apple-pies/",
    description: "Individual filo pastry cups filled with cinnamon-spiced apple.",
    servings: 6,
    servingSizeGrams: 114,
    vegetableServes: 0,
    fruitServes: 0.5,
    tags: ["Snack", "Sweet", "Vegetarian", "Nut Free"],
    ingredients: ["3 tsp canola oil", "1 tsp ground cinnamon", "½ lemon, juiced", "3 medium apples, diced", "6 sheets filo pastry, thawed", "2 tbsp low-fat milk"],
    instructions: ["Pre-heat oven to 180°C (160°C fan-forced). Lightly brush six muffin holes with 1 tsp oil.", "Heat remaining oil and cinnamon in a saucepan over moderate heat.", "Add apple and lemon juice, reduce heat to low and cook for 10 minutes, stirring occasionally.", "Layer six sheets of filo, brushing each layer lightly with milk, then cut into six squares.", "Press pastry squares into the muffin holes and divide apple mixture between them.", "Bake for 15 minutes or until golden brown. Cool slightly before serving."],
    notes: ["Serve with low-fat Greek yoghurt if desired.", "Refrigerate in an airtight container for up to 2 days."],
    nutrition: { energyKj: 490, fatGrams: 2.9, saturatedFatGrams: 0.3, carbsGrams: 18.5, sugarGrams: 10.7, fibreGrams: 3.2, proteinGrams: 1.9, sodiumMg: 85 },
  },
  {
    id: "hwq-banana-blueberry-pikelets",
    name: "Banana and Blueberry Pikelets",
    style: "Sweet",
    imageUrl: "/recipes/hwq/banana-blueberry-pikelets.webp",
    sourceUrl: "https://hw.qld.gov.au/healthy-recipes/banana-and-blueberry-pikelets/",
    description: "Banana and blueberry pikelets for breakfast, lunchboxes or afternoon snacks.",
    servings: 8,
    servingSizeGrams: 117,
    vegetableServes: 0.5,
    fruitServes: 0,
    tags: ["Snack", "Sweet", "Vegetarian", "Nut Free", "Lunchbox"],
    ingredients: ["1 cup reduced-fat milk", "1 large egg", "3 medium ripe bananas, mashed thoroughly", "1½ cups all-purpose flour", "1½ tsp baking powder", "1½ cups frozen blueberries", "1 tsp canola oil"],
    instructions: ["Mash bananas thoroughly in a medium bowl.", "Add milk and egg and mix together.", "Add flour and baking powder and mix.", "Fold through blueberries gently.", "Heat oil in a frypan over medium heat. Spoon about 2 tablespoons mixture per pikelet and cook about 2 minutes until firm and golden underneath.", "Turn and cook for another 2 minutes or until golden."],
    notes: ["For dairy free, use a calcium-fortified dairy-free milk alternative.", "For gluten free, use gluten-free flour and check the baking powder is gluten free.", "Blueberries can be swapped for blackberries or grated apple.", "Serve as is or with Greek yoghurt."],
    nutrition: { energyKj: 653, fatGrams: 2, saturatedFatGrams: 0.5, carbsGrams: 28.2, sugarGrams: 7.9, fibreGrams: 2, proteinGrams: 5.1, sodiumMg: 82.8 },
  },
  {
    id: "hwq-carrot-cake-oat-bars",
    name: "Carrot Cake Oat Bars",
    style: "Sweet",
    imageUrl: "/recipes/hwq/carrot-cake-oat-bars.webp",
    sourceUrl: "https://hw.qld.gov.au/healthy-recipes/carrot-cake-oat-bars/",
    description: "Oat and carrot squares flavoured with ginger, nutmeg and orange.",
    servings: 9,
    servingSizeGrams: 100,
    vegetableServes: 0.5,
    fruitServes: 0,
    tags: ["Snack", "Sweet", "Vegetarian", "Dairy Free", "Nut Free"],
    ingredients: ["1 cup quick oats", "½ cup wholemeal self-raising flour", "1 tsp ground ginger", "½ tsp ground nutmeg", "2 eggs, whisked", "1½ tbsp canola oil", "1½ tbsp honey", "½ orange, juiced and zested", "3 large carrots, grated"],
    instructions: ["Pre-heat oven to 200°C (180°C fan-forced). Line a 20cm x 20cm square tin with baking paper.", "Combine oats, flour, ginger and nutmeg in a large bowl.", "Make a well and add eggs, oil, honey, orange juice, orange zest and carrot. Mix together.", "Pour into the prepared pan and bake for 25–30 minutes or until firm to touch.", "Cool on a wire rack and slice into 9 pieces."],
    notes: ["Serve with low-fat Greek yoghurt or a piece of fresh fruit if desired.", "Refrigerate airtight for up to 3 days or freeze individual slices for up to 2 months."],
    nutrition: { energyKj: 593, fatGrams: 4.9, saturatedFatGrams: 0.7, carbsGrams: 18.9, sugarGrams: 8.4, fibreGrams: 4.3, proteinGrams: 3.7, sodiumMg: 94 },
  },
  {
    id: "hwq-apple-cinnamon-bliss-balls",
    name: "Apple Cinnamon Bliss Balls",
    style: "Sweet",
    imageUrl: "/recipes/hwq/apple-cinnamon-bliss-balls.webp",
    sourceUrl: "https://hw.qld.gov.au/healthy-recipes/apple-cinnamon-bliss-balls/",
    description: "Apple, oat and peanut butter bliss balls with cinnamon and coconut.",
    servings: 10,
    servingSizeGrams: 57,
    vegetableServes: 0,
    fruitServes: 0.5,
    tags: ["Snack", "Sweet", "Vegan", "Dairy Free"],
    ingredients: ["1 medium apple, grated", "150g dried apple pieces, roughly chopped", "¼ cup smooth all-natural peanut butter", "1 tsp vanilla extract", "¼ cup water", "1¼ cups rolled oats", "1 tsp ground cinnamon", "1 tbsp desiccated coconut"],
    instructions: ["Line a large baking tray with baking paper.", "Process grated apple, dried apple, peanut butter, vanilla and water until combined, then transfer to a large bowl.", "Process oats and cinnamon until combined and add to the bowl.", "Mix everything together.", "Place coconut on a plate. Roll heaped tablespoons of mixture into 20 balls and coat lightly in coconut.", "Transfer to the tray and refrigerate for 1 hour or until firm."],
    notes: ["For nut free, replace peanut butter with tahini paste.", "Refrigerate in an airtight container for up to 5 days."],
    nutrition: { energyKj: 570, saturatedFatGrams: 1.1, carbsGrams: 16.8, sugarGrams: 10.6, fibreGrams: 4.2, proteinGrams: 3.5, sodiumMg: 51 },
  },
  {
    id: "hwq-pumpkin-scones",
    name: "Pumpkin Scones",
    style: "Sweet",
    imageUrl: "/recipes/hwq/pumpkin-scones.webp",
    sourceUrl: "https://hw.qld.gov.au/healthy-recipes/pumpkin-scones/",
    description: "Mini wholemeal pumpkin scones with nutmeg and sultanas.",
    servings: 10,
    servingSizeGrams: 83,
    vegetableServes: 0.5,
    fruitServes: 0,
    tags: ["Snack", "Sweet", "Vegetarian", "Nut Free"],
    ingredients: ["375g butternut pumpkin, peeled and chopped", "1 tbsp butter", "1¼ cups wholemeal self-raising flour", "¾ cup self-raising flour", "½ tsp ground nutmeg", "1 tbsp sultanas", "½ cup low-fat milk, plus extra to brush"],
    instructions: ["Pre-heat oven to 200°C (180°C fan-forced) and line a large tray with baking paper.", "Boil pumpkin for 10 minutes or until tender, then drain well.", "Mash pumpkin and butter together until smooth.", "Sift in both flours and nutmeg, add sultanas and milk and mix lightly.", "Turn onto a lightly floured surface and knead gently until combined.", "Shape into a rectangle about 2cm thick, cut 10 rounds with a 4cm cutter and place on the tray.", "Brush lightly with milk and bake for 15–18 minutes or until golden and firm. Cool on a wire rack."],
    notes: ["For gluten free, replace both flours with gluten-free self-raising flour.", "If you do not have a scone cutter, use a small cup as a guide.", "Refrigerate airtight for up to 2 days or freeze individually for up to 3 months."],
    nutrition: { energyKj: 580, fatGrams: 2.5, saturatedFatGrams: 1.3, carbsGrams: 23.1, sugarGrams: 3.9, fibreGrams: 3, proteinGrams: 4.2, sodiumMg: 196 },
  },
  {
    id: "hwq-tropical-frozen-yoghurt-bites",
    name: "Tropical Frozen Yoghurt Bites",
    style: "Sweet",
    imageUrl: "/recipes/hwq/tropical-frozen-yoghurt-bites.webp",
    sourceUrl: "https://hw.qld.gov.au/healthy-recipes/tropical-frozen-yoghurt-bites/",
    description: "Frozen yoghurt bites made with banana, passionfruit and pineapple.",
    servings: 6,
    servingSizeGrams: 146,
    vegetableServes: 0,
    fruitServes: 0.5,
    tags: ["Snack", "Sweet", "Vegetarian", "Gluten Free", "Nut Free"],
    ingredients: ["3 ripe bananas, mashed", "2 passionfruit, pulp retained", "227g canned crushed pineapple in juice, drained", "1½ cups low-fat Greek yoghurt"],
    instructions: ["Combine all ingredients in a large mixing bowl.", "Using an electric mixer, mix on low speed for about 30 seconds until smooth and evenly combined.", "Spoon into two 12-slot ice cube trays and smooth the tops. Insert a wooden stick into each slot if desired.", "Freeze for about 3 hours or until firm and set, then serve immediately."],
    notes: ["For dairy free, use a calcium-fortified dairy-free yoghurt alternative.", "Mash and stir by hand if you do not have an electric mixer.", "Ice-block moulds can be used instead of ice cube trays.", "Use 4–6 cubes blended with a cup of low-fat milk as a smoothie base."],
    nutrition: { energyKj: 509, fatGrams: 1.6, saturatedFatGrams: 0.9, carbsGrams: 18.1, sugarGrams: 14.7, fibreGrams: 3.7, proteinGrams: 5.9, sodiumMg: 74 },
  },
  {
    id: "hwq-strawberry-parfait",
    name: "Strawberry Parfait",
    style: "Sweet",
    imageUrl: "/recipes/hwq/strawberry-parfait.webp",
    sourceUrl: "https://hw.qld.gov.au/healthy-recipes/layered-strawberry-parfait/",
    description: "A layered strawberry, oat and Greek yoghurt parfait with chia and pumpkin seeds.",
    servings: 4,
    servingSizeGrams: 147,
    vegetableServes: 0,
    fruitServes: 0.4,
    tags: ["Snack", "Sweet", "Vegetarian", "Nut Free"],
    ingredients: ["250g strawberries, chopped", "½ cup rolled oats", "1 tbsp chia seeds", "1 tbsp pumpkin seeds", "1 cup reduced-fat Greek yoghurt", "1 tsp honey", "A pinch of cinnamon"],
    instructions: ["Add strawberries to the bottom of a glass or bowl.", "Sprinkle with a tablespoon of rolled oats.", "Add a layer of yoghurt, then sprinkle with chia seeds and pumpkin seeds.", "Repeat layers until the glass is full or ingredients are used up.", "Drizzle honey on top and garnish with strawberries and a pinch of cinnamon."],
    notes: ["Fresh strawberries can be swapped for frozen.", "For a compote, simmer 1 cup frozen strawberries with ¼ cup water and 1 tsp honey until reduced.", "Cover assembled leftovers and refrigerate for up to 1 day."],
    nutrition: { energyKj: 628, fatGrams: 5, saturatedFatGrams: 1.4, carbsGrams: 14.9, sugarGrams: 9.4, fibreGrams: 5.5, proteinGrams: 8, sodiumMg: 73.3 },
  },
];
